#!/usr/bin/env python3

from guesttemplates import loader
import XenAPI
import errno

if __name__ == '__main__':
    try:
        session = XenAPI.xapi_local()
        session.xenapi.login_with_password('', '', '', 'create-template')

        loader = loader.Loader(session)
        loader.find_config_files("/usr/share/xapi/vm-templates",
                                 "/etc/xapi.d/vm-templates")
        loader.load_templates()
        loader.remove_default_templates()
        loader.insert_templates()

        session.xenapi.session.logout()
    except IOError as e:
        # If running during host installation, XAPI won't be available so just
        # fail silently.
        if e.errno in (errno.ECONNREFUSED, errno.ENOENT):
            exit(1)
        raise
